name: Push scheduled postgres

# This workflow is necessary because PostgreSQL frequently updates its base image without specifying a patch level.
# As a result, we must perform weekly checks for any new images.

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 3'  # Runs at 00:00 every Wednesday

jobs:
  upgrade-postgres:
    strategy:
      fail-fast: false
      # We have to run one workflow after the other here
      # because our product compose Construction Process cannot handle multiple processes.
      max-parallel: 1
      matrix:
        include:
          - postgres-major-version: 16
            services: '["asset-management-postgres", "opensight-keycloak-postgres", "scan-management-postgres", "vulnerability-intelligence-postgres", "opensight-notification-service-postgres", "management-console-postgres"]'
    uses: ./.github/workflows/push-compare.yml
    with:
      postgres-major-version: ${{ matrix.postgres-major-version }}
      services: ${{ matrix.services }}
    secrets: inherit

  notify:
    needs:
      - upgrade-postgres
    if: ${{ !cancelled() }}
    uses: greenbone/workflows/.github/workflows/notify-mattermost-3rd-gen.yml@main
    with:
      status: ${{ contains(needs.*.result, 'failure') && 'failure' || 'success' }}
    secrets: inherit
